- name: collect heap dump from all datagrid containers
  hosts: 127.0.0.1
  connection: local
  tasks:
  - name: 
    shell: sh ../scripts/datagrid/get_datagrid_heap_dump.sh
    async: 600
    poll: 0 
