---
- name: Playbook master RHSSO. PLEASE  "RUN  ps aux | grep get_sso"  to see all collect process running
  hosts: 127.0.0.1
  tasks:

# Set Log TRACE (This is a optional script, if requested by support)
#- import_playbook: rhsso/set_trace-logs_sso.yaml

# COLLECT THREAD DUMP ASYNC (This playbook will run in paralel mode, and will killed after time in async "seconds"  to view script running, type this command "ps aux | grep .sh")
- import_playbook: rhsso/collect_thread_dump.yaml

# COLLECT HEAP DUMP ASYNC (This playbook will run in paralel mode, and will killed after time in async "seconds"  to view script running, type this command "ps aux | grep .sh")
- import_playbook: rhsso/collect_heap_dump.yaml

#Collect informations about cpu and memory Openshift nodes and Openshift pods
- import_playbook: rhsso/collect_ocp_info.yaml

# COLLECT CONFIG FILES SSO
- import_playbook: rhsso/collect_config_sso.yaml

#COLLECT LOGS SSO (This script collect all logs in log directories, gc , server, audit, etc.... )
- import_playbook: rhsso/collect_logs_sso.yaml

# UNSET TRACE LOGS (This script needs run if you SET log as TRACE earlier)
#- import_playbook: rhsso/unset_trace-logs_sso.yaml
